name: Nuxt.js CI

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

    #   - name: Run lint
    #     run: npm run lint

    #   - name: Run tests
    #     run: npm run test

      - name: Build project
        run: npm run build

  build-deploy-heroku:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Heroku container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Build, Push and Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          docker build --build-arg PORT=${{ secrets.PORT }} \
                      --build-arg BE_BASE_URL=${{ secrets.BE_BASE_URL }} \
                      --build-arg DATA_CLIENT_MIDTRANS=${{ secrets.DATA_CLIENT_MIDTRANS }} \
                      -t registry.heroku.com/$HEROKU_APP_NAME/web .
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
          heroku container:release web --app $HEROKU_APP_NAME
      
      - name: Push to Docker Hub
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag registry.heroku.com/$HEROKU_APP_NAME/web $DOCKER_USERNAME/$DOCKER_REPO:${TIMESTAMP}
          docker push $DOCKER_USERNAME/$DOCKER_REPO:${TIMESTAMP}
          docker tag $DOCKER_USERNAME/$DOCKER_REPO:${TIMESTAMP} $DOCKER_USERNAME/$DOCKER_REPO:latest
          docker push $DOCKER_USERNAME/$DOCKER_REPO:latest
